### ISSUE TITLE
Prism towers do not combine beams

### ISSUE THREAD

**Issue by ghost** [phrohdoh/OpenRA#29] opened 2015-10-30 02:29 UTC
In RA2, multiple nearby prism towers would combine their shots into one larger beam. This needs to be implemented.

Revision: 41d9a20

**Comment by Mailaender** [comment] 2016-02-21 21:37
Reverse duplicate of https://github.com/OpenRA/ra2/issues/133.

**Closed as completed** 2016-02-22 02:02 UTC
