### ISSUE TITLE
Buildings have weird z-ordering.

### ISSUE THREAD

**Issue by ghost** [phrohdoh/OpenRA#60] opened 2015-11-01 01:23 UTC
Some known examples:
- An allied War Factory will be drawn on top of a vehicle stationed immediately southwest of it.
- Man buildings are inconsistently drawn above and/or below the overlay for the Iron Curtain support power.

**Comment by penev92** [comment] 2015-11-01 10:51
There is no proper Z-sorting in OpenRA yet. That is still being worked on.

**Comment by phrohdoh** [comment] 2015-11-01 14:02
Z-Sorting does exist in the way of `ZOffset` for sequences.

**Comment by Mailaender** [comment] 2016-02-21 21:30
Reverse duplicate of https://github.com/OpenRA/ra2/issues/127.

**Closed as completed** 2016-02-22 02:01 UTC
